name: 'test'
on:
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/*']
  push:
    branches: ['main', 'aix']

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-latest', 'ubuntu-24.04-arm']
        go: ['1.19', '1.24']
    runs-on: '${{ matrix.os }}'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with: {go-version: '${{ matrix.go }}'}
      - name: test
        run: |
          go version
          FSNOTIFY_BUFFER=4096 go test -parallel 1 -race    ./...
                               go test -parallel 1 -race    ./...
          FSNOTIFY_DEBUG=1     go test -parallel 1 -race -v ./...
